rock.namespace('app');

app.constants = {
    LOCALE_EN : 'en',

    RESOURCE_LOADER_WINDOW : 'RESOURCE_LOADER_WINDOW',
    MAIN_WINDOW : 'MAIN_WINDOW',
    SHOW_MODEL_WINDOW : 'SHOW_MODEL_WINDOW',
    SHOW_SCENE_WINDOW : 'SHOW_SCENE_WINDOW',

    RES_ID_MODEL_TEAPOT : 'RES_ID_MODEL_TEAPOT',
    RES_ID_MODEL_TEAPOT_TITLE : 'RES_ID_MODEL_TEAPOT_TITLE',
    RES_ID_MODEL_STARWARS_TITLE : 'RES_ID_MODEL_STARWARS_TITLE',
    RES_ID_MODEL_GROUND : 'RES_ID_MODEL_GROUND',
    RES_ID_MODEL_SKYDOME : 'RES_ID_MODEL_SKYDOME',
    RES_ID_MODEL_STORMTROOPER : 'RES_ID_MODEL_STORMTROOPER',
    RES_ID_MODEL_C3PO : 'RES_ID_MODEL_C3PO',
    RES_ID_MODEL_R2D2 : 'RES_ID_MODEL_R2D2',
    RES_ID_MODEL_DARTHSIDIOUS : 'RES_ID_MODEL_DARTHSIDIOUS',

    RES_TEXTURE_TITLE_TEAPOT : 'teapotTitle.png',
    RES_TEXTURE_SKYDOME : 'skydome.png',
    RES_TEXTURE_TITLE_STARWARS : 'starwarsTitle.png',
    RES_TEXTURE_STORMTROOPER : 'stormtrooper.png',
    RES_TEXTURE_STORMTROOPER_S : 'stormtrooper_S.png',
    RES_TEXTURE_C3PO : 'C-3PO.png',
    RES_TEXTURE_C3PO_S : 'C-3PO_S.png',
    RES_TEXTURE_R2D2 : 'R2-D2.png',
    RES_TEXTURE_R2D2_S : 'R2-D2_S.png',
    RES_TEXTURE_DARTHSIDIOUS : 'DarthSidious.png'

};
