rock.namespace('rock.game');

/**
 * Constants for use with rock game
 *
 * @constructor
 * @author Luis Alberto Jiménez
 */
rock.game.constants = {
    GROUP_MODEL_TYPE: 'GROUP_MODEL_TYPE',

    NO_LIGHTING_NEEDED_TYPE: 'NO_LIGHTING_NEEDED_TYPE',
    DIRECTIONAL_LIGHTING_TYPE: 'DIRECTIONAL_LIGHTING_TYPE',
    POINT_LIGHTING_TYPE: 'POINT_LIGHTING_TYPE',
    SPOTLIGHT_LIGHTING_TYPE: 'SPOTLIGHT_LIGHTING_TYPE',

    COLOR_MODEL_TYPE: 'COLOR_MODEL_TYPE',
    TEXTURE_MODEL_TYPE: 'TEXTURE_MODEL_TYPE',
    PHONG_MODEL_TYPE: 'PHONG_MODEL_TYPE',
    PHONG_TEXTURE_MODEL_TYPE: 'PHONG_TEXTURE_MODEL_TYPE',

    ROCK_BASIC_RENDERER_CONTEXT_ID: 'ROCK_BASIC_RENDERER_CONTEXT_ID'
};